### ISSUE TITLE
Burp Crashing while loading Extension

### ISSUE THREAD

**Issue by ehsandeep** [yandex/burp-molly-scanner#1]
Hello, 

Thanks for doing this, I was trying to install this, so as per description, created build using Maven

 
![image](https://user-images.githubusercontent.com/8293321/32979792-9f296a04-cc81-11e7-98ec-b58e5a52c219.png)

While adding the extension, I tried to add or enable it and it causing the Burp Crash, can you look into this?

![2017-11-18_17-04-48](https://user-images.githubusercontent.com/8293321/32979856-a70efb5c-cc82-11e7-8215-4369e6258cd0.gif)

**Comment by kyprizel** [comment]
It does not crashes - it intentionally exits.
You shouldn't run the extension without a config file (see examples and run.sh).

**Comment by lianfeng30** [comment]
i have the same error
BurpSuite have down...
what i should do ?

**Comment by kyprizel** [comment]
Just delete the jar to disable the plugin.

**Comment by lianfeng30** [comment]
@kyprizel  thanks

**Comment by lianfeng30** [comment]
@kyprizel  
how to used the plugin?

**Comment by lianfeng30** [comment]
What does it mean? How to modify the configuration? "Change and save burp_molly_config.json" ?

**Comment by kyprizel** [comment]
Save it to some arbitary place and pass the path as MOLLY_CONFIG environment variable.

**Comment by lianfeng30** [comment]
@kyprizel 
en... but It crashes also - it exits...

**Comment by lianfeng30** [comment]
@kyprizel 
vim ~/.bash_profile

![image](https://user-images.githubusercontent.com/8369618/33006736-22f1ab84-cd91-11e7-87bc-b68f9be8d28b.png)

and i Run Burp Suite in console java -jar burpsuite_pro.jar
Add Plugins Jar file in Extender Tab
then it crashes also,it exits

**Comment by kyprizel** [comment]
Try to run:
java -jar burpsuite_pro.jar --molly-config=/Users/xxx/Downloads/burp_molly_config.json

**Comment by lianfeng30** [comment]
@kyprizel OK

**Comment by ehsandeep** [comment]
Hello @kyprizel, 

Got scanning thing working, anyway was running this on Windows environment so got following error:

![image](https://user-images.githubusercontent.com/8293321/33086683-5d1818e2-cf0e-11e7-8431-131bd0669cff.png)

is it supposed to be run on Linux environment only?

**Comment by kyprizel** [comment]
just change the report_path in config file

**Comment by ehsandeep** [comment]
Hey @kyprizel,

Yes, noticed that, Thanks!

Along with that, Can be set other authenticated cookies as well same as **User-Agent in the config file**? and **same for the custom header** as well?

Sample format for **setup authenticated cookies and custom header** in the config file will be helpful.

Thank you.
