### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by Teicu** [yandex/burp-molly-scanner#2]
"The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version."

What version I need? 

I have now: 

java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode) 

Thanks again

**Comment by kyprizel** [comment]
> java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
